apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ci-test-stack.consoleSAName" . }}
  labels:
    {{- include "ci-test-stack.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ci-test-stack.consoleSAName" . }}-token
  annotations:
    kubernetes.io/service-account.name: {{ include "ci-test-stack.consoleSAName" . }}
  labels:
    {{- include "ci-test-stack.labels" . | nindent 4 }}
type: kubernetes.io/service-account-token
