apiVersion: v1
kind: Service
metadata:
  name: {{ include "ci-test-stack.consoleName" . }}
  labels:
    {{- include "ci-test-stack.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "ci-test-stack.consoleName" . }}
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
