apiVersion: v1
kind: Service
metadata:
  name: {{ include "ci-test-stack.pluginName" . }}
  labels:
    {{- include "ci-test-stack.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "ci-test-stack.pluginName" . }}
  ports:
    - port: {{ .Values.pluginPort }}
      targetPort: 8080
      protocol: TCP
