FROM registry.access.redhat.com/ubi9/nodejs-18:latest AS build

USER 0
COPY . /opt/app-root/src/app
WORKDIR /opt/app-root/src/app
RUN npm ci && npm run build

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

RUN microdnf install -y nginx && microdnf clean all && \
    chown -R 1001:0 /var/lib/nginx /var/log/nginx /run && \
    chmod -R ug+rwX /var/lib/nginx /var/log/nginx /run

USER 1001

COPY --from=build /opt/app-root/src/app/dist /opt/app-root/src

CMD nginx -g "daemon off;"
