export const VM_NETWORK_TABLE_COLUMN_IDS = {
  ACTIONS: 'actions',
  CONDITIONS: 'conditions',
  CPU: 'cpu',
  CREATED: 'created',
  DELETION_PROTECTION: 'deletionProtection',
  INTERFACE: 'interface',
  MEMORY: 'memory',
  NAME: 'name',
  NAMESPACE: 'namespace',
  STATUS: 'status',
} as const;

export type VMNetworkTableColumnId =
  (typeof VM_NETWORK_TABLE_COLUMN_IDS)[keyof typeof VM_NETWORK_TABLE_COLUMN_IDS];

export const VM_NETWORK_TABLE_SORTABLE_COLUMN_IDS = [
  VM_NETWORK_TABLE_COLUMN_IDS.NAME,
  VM_NETWORK_TABLE_COLUMN_IDS.NAMESPACE,
  VM_NETWORK_TABLE_COLUMN_IDS.STATUS,
  VM_NETWORK_TABLE_COLUMN_IDS.INTERFACE,
  VM_NETWORK_TABLE_COLUMN_IDS.CREATED,
  VM_NETWORK_TABLE_COLUMN_IDS.MEMORY,
  VM_NETWORK_TABLE_COLUMN_IDS.CPU,
  VM_NETWORK_TABLE_COLUMN_IDS.CONDITIONS,
  VM_NETWORK_TABLE_COLUMN_IDS.DELETION_PROTECTION,
] as const;
