import { VM_NETWORKS_OTHER_TYPES_PATH, VM_NETWORKS_PATH } from '../constants';

export const TAB_INDEXES = {
  OTHER_VM_NETWORK_TYPES: 1,
  OVN_LOCALNET: 0,
};

export const TAB_INDEX_BY_PATH = {
  [VM_NETWORKS_OTHER_TYPES_PATH]: TAB_INDEXES.OTHER_VM_NETWORK_TYPES,
  [VM_NETWORKS_PATH]: TAB_INDEXES.OVN_LOCALNET,
};

export const PATH_BY_TAB_INDEX = {
  [TAB_INDEXES.OTHER_VM_NETWORK_TYPES]: VM_NETWORKS_OTHER_TYPES_PATH,
  [TAB_INDEXES.OVN_LOCALNET]: VM_NETWORKS_PATH,
};
